[metadata]
name = corext
version = attr: corext.__version__
description = COREX: A complete language model built from scratch
long_description = file: README.md
long_description_content_type = text/markdown
author = 
license_files = LICENSE

[options]
package_dir =
    = src
packages = find:

[options.packages.find]
where = src
